# Generated by Django 2.2.6 on 2019-10-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_auto_20191018_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='room_available',
        ),
        migrations.AddField(
            model_name='bookings',
            name='manager_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Manager'),
        ),
    ]
