# Generated by Django 2.2.6 on 2019-10-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_auto_20191018_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='is_room_available',
        ),
        migrations.AddField(
            model_name='rooms',
            name='no_of_members',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
